-- MySQL Script generated by MySQL Workbench
-- Fri May 27 00:42:56 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema employees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees` DEFAULT CHARACTER SET utf8 ;
USE `employees` ;

-- -----------------------------------------------------
-- Table `employees`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`departments` (
  `dept_no` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dept_no`),
  UNIQUE INDEX `dept_name` (`dept_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `employees`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`employees` (
  `emp_no` BIGINT NOT NULL AUTO_INCREMENT,
  `birth_date` DATE NOT NULL,
  `first_name` VARCHAR(14) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `employees`.`dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`dept_emp` (
  `emp_no` BIGINT NOT NULL,
  `dept_no` CHAR(4) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  INDEX `emp_no` (`emp_no` ASC),
  INDEX `dept_no` (`dept_no` ASC),
  CONSTRAINT `dept_emp_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employees` (`emp_no`)
    ON DELETE CASCADE,
  CONSTRAINT `dept_emp_ibfk_2`
    FOREIGN KEY (`dept_no`)
    REFERENCES `employees`.`departments` (`dept_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `employees`.`dept_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`dept_manager` (
  `dept_no` CHAR(4) NOT NULL,
  `emp_no` BIGINT NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `dept_no`),
  INDEX `emp_no` (`emp_no` ASC),
  INDEX `dept_no` (`dept_no` ASC),
  CONSTRAINT `dept_manager_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employees` (`emp_no`)
    ON DELETE CASCADE,
  CONSTRAINT `dept_manager_ibfk_2`
    FOREIGN KEY (`dept_no`)
    REFERENCES `employees`.`departments` (`dept_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `employees`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`salaries` (
  `emp_no` BIGINT NOT NULL,
  `salary` INT(11) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `from_date`),
  INDEX `emp_no` (`emp_no` ASC),
  CONSTRAINT `salaries_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employees` (`emp_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `employees`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`titles` (
  `emp_no` BIGINT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_no`, `title`, `from_date`),
  INDEX `emp_no` (`emp_no` ASC),
  CONSTRAINT `titles_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employees` (`emp_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
